# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=200)),
                ('cid', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('numero_copias', models.IntegerField()),
                ('numero_hojas', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
